# Generated by Django 4.1.7 on 2023-02-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.CharField(max_length=100)),
                ("content", models.TextField(max_length=1000)),
                ("created", models.DateTimeField(verbose_name="date published")),
            ],
        ),
    ]
